name: newcampusconnect
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.4
  cloud_firestore: ^4.17.2
  image_picker: ^1.0.7
  get: ^4.6.6
  google_sign_in: ^6.2.1
  firebase_database: ^10.5.4
  animated_splash_screen: ^1.3.0
  page_transition: ^2.1.0
  firebase_storage: ^11.7.5
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
 

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/images/
